### ISSUE TITLE
"rubygems explanation" link is broken

### ISSUE THREAD

**Issue by ethagnawl** [joonty/pessimize#19]
The README currently contains a link to "[rubygems explanation](http://docs.rubygems.org/read/chapter/16#page74)", but that link no longer works.

Is anyone aware of an alternative resource? If not, the link could point towards [the last Internet Archive snapshot](https://web.archive.org/web/20130705055345/http://docs.rubygems.org/read/chapter/16) of the page.

**Comment by randallreedjr** [comment]
It looks like this might be the updated relevant documentation: http://guides.rubygems.org/patterns/#semantic-versioning

**Comment by joonty** [comment]
Fixed by #20
