### ISSUE TITLE
Strange Behaviour

### ISSUE THREAD

**Issue by Undistraction** [joonty/pessimize#9]
Problems:

Before:
```
gem "seedbank", "~> 0.3.0.pre"
gem "high_voltage"
```

After:
```
gem "seedbank", '0.2'
gem "high_voltage" # Still no version
```

**Comment by joonty** [comment]
Hi @Undistraction,

Pessimize is now at version 0.3.0, which has undergone some major changes and crucially doesn't change the formatting of your Gemfile.

I'm going to close this now, but do please check out the latest version, and if by some chance you're still experiencing problems then feel free to reopen this issue or a new one.

Thanks very much.
